version: '3'

tasks:
  default:
    desc: 默认运行开发服务器
    cmds:
      - task: run

  format:
    desc: 格式化 Dart 代码
    cmds:
      - dart format .

  run:
    desc: 运行 Flutter 应用
    cmds:
      - flutter run

  build:
    desc: 构建 Linux 应用
    cmds:
      - flutter build linux

  test:
    desc: 运行测试
    cmds:
      - flutter test

  check:
    desc: 代码分析
    cmds:
      - flutter analyze

  clean:
    desc: 清理构建文件
    cmds:
      - flutter clean

  go:
    desc: 运行 Go 可执行文件
    cmds:
      - ./go/bin/学习平台

  rel:
    desc: 构建发布版本（需要指定版本号参数）
    cmds:
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "错误：请指定版本号"
          echo "用法task rel -- <版本号>"
          echo "示例task rel -- 1.0.0"
          exit 1
        fi
        VERSION={{.CLI_ARGS}}
        mkdir -p "release/StudyPlatformv${VERSION}"
        bash -c "read -n 1 -p \"请把macOS与Windows构建zip放入release/StudyPlatformv${VERSION}后按任意键继续...\" -s"
        echo
        flutter build linux --release
        mkdir -p release/raw
        cp -rv build/linux/x64/release/bundle "release/v${VERSION}"
        tar cavf "release/StudyPlatformv${VERSION}/linux.tar.zst" "release/v${VERSION}"
        mv "release/v${VERSION}" "release/raw/v${VERSION}"
        gh release create v$VERSION
        gh release upload v$VERSION release/StudyPlatformv$VERSION/*
  
  upl: 
    desc: 上传版本到指定release
    cmds: 
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "错误：请指定版本号"
          exit 1
        fi
        VERSION={{.CLI_ARGS}}
        gh release upload v$VERSION release/StudyPlatformv$VERSION.tar.xz
  
  view: 
    desc: 查看指定版本release
    cmds: 
      - |
        if [ -z "{{.CLI_ARGS}}" ]; then
          echo "错误：请指定版本号"
          exit 1
        fi
        VERSION={{.CLI_ARGS}}
        gh release view v$VERSION
  
  analyze: 
    desc: 分析代码
    cmds: 
      - flutter analyze
  
  get: 
    desc: 获取依赖
    cmds: 
      - flutter pub get
  
