import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:study_platform/pages/pages.dart';

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  List<String> routes() {
    return [
      '/',
      '/apage',
      '/apage/gpage',
      '/apage/gpage/wenpage',
      '/apage/gpage/wenpage/zhengpage',
      '/apage/gpage/wupage',
      '/apage/gpage/wupage/zengpage',
      '/apage/gpage/wupage/zhaopage',
      '/apage/juanpage',
      '/apage/juanpage/guwanpage',
      '/apage/shoppage',
      '/apage/shoppage/baopage',
      '/apage/shoppage/bookpage',
      '/apage/shoppage/easypage',
      '/apage/shoppage/easypage/baipage',
      '/apage/shoppage/easypage/jinpage',
      '/apage/shoppage/easypage/tongpage',
      '/apage/shoppage/gupage',
      '/apage/shoppage/simplepage',
      '/apage/thingpage',
      '/apage/thingpage/baowupage',
      '/apage/thingpage/bookpage',
      '/apage/thingpage/caipage',
      '/apage/thingpage/dresspage',
      '/apage/thingpage/dresspage/paopage',
      '/apage/thingpage/dresspage/swordpage',
      '/apage/thingpage/guwanpage',
      '/apage/usepage',
      '/apage/usepage/baopage',
      '/bankpage',
      '/bankpage/getpage',
      '/bankpage/juanpage',
      '/bankpage/juanpage/jiangpage',
      '/bankpage/juanpage/jiangpage/jifenpage',
      '/bankpage/juanpage/realpage',
      '/bankpage/storepage',
      '/calcpage',
      '/calcpage/shoppage',
      '/calcpage/startpage',
      '/calcpage/startpage/addsubpage',
      '/calcpage/startpage/divpage',
      '/calcpage/startpage/polypage',
      '/calcpage/startpage/timpage',
      '/ownpage',
      '/ownpage/lihepage',
      '/ownpage/thingpage',
      '/ownpage/thingpage/mainpage',
      '/ownpage/thingpage/mainpage/baoshipage',
      '/ownpage/thingpage/mainpage/baoshipage/getpage',
      '/ownpage/thingpage/mainpage/baoshipage/cpage',
      '/ownpage/thingpage/mainpage/baoshipage/cpage/c1page',
      '/ownpage/thingpage/mainpage/cardpage',
      '/ownpage/thingpage/mainpage/cardpage/han1page',
      '/ownpage/thingpage/mainpage/cardpage/sang1page',
      '/ownpage/thingpage/mainpage/yinbipage',
      '/ownpage/thingpage/shoppage',
      '/ownpage/thingpage/showpage',
      '/ownpage/timepage',
      '/ownpage/tongypage',
      '/ownpage/tongypage/jifenpage',
      '/settingpage',
      '/thingpage',
      '/thingpage/freepage',
      '/thingpage/jinpage',
      '/thingpage/mangpage',
      '/utilpage',
    ];
  }

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(
        title: '学习平台',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        initialRoute: '/',
        routes: {
          '/': (context) => HomePage(),
          '/apage': (context) => APage(),
          '/apage/gpage': (context) => AGPage(),
          '/apage/gpage/wenpage': (context) => AGWenPage(),
          '/apage/gpage/wenpage/zhengpage': (context) => AGWenZhengPage(),
          '/apage/gpage/wupage': (context) => AGWuPage(),
          '/apage/gpage/wupage/zengpage': (context) => AGWuZengPage(),
          '/apage/gpage/wupage/zhaopage': (context) => AGWuZhaoPage(),
          '/apage/juanpage': (context) => AJuanPage(),
          '/apage/juanpage/guwanpage': (context) => AJuanGuwanPage(),
          '/apage/shoppage': (context) => AShopPage(),
          '/apage/shoppage/baopage': (context) => AShopBaoPage(),
          '/apage/shoppage/bookpage': (context) => AShopBookPage(),
          '/apage/shoppage/easypage': (context) => AShopEasyPage(),
          '/apage/shoppage/easypage/baipage': (context) => AShopEasyBaiPage(),
          '/apage/shoppage/easypage/jinpage': (context) => AShopEasyJinPage(),
          '/apage/shoppage/easypage/tongpage': (context) => AShopEasyTongPage(),
          '/apage/shoppage/gupage': (context) => AShopGuPage(),
          '/apage/shoppage/simplepage': (context) => AShopSimplePage(),
          '/apage/thingpage': (context) => AThingPage(),
          '/apage/thingpage/baowupage': (context) => AThingBaowuPage(),
          '/apage/thingpage/bookpage': (context) => AThingBookPage(),
          '/apage/thingpage/caipage': (context) => AThingCaiPage(),
          '/apage/thingpage/dresspage': (context) => AThingDressPage(),
          '/apage/thingpage/dresspage/paopage': (context) =>
              AThingDressPaoPage(),
          '/apage/thingpage/dresspage/swordpage': (context) =>
              AThingDressSwordPage(),
          '/apage/thingpage/guwanpage': (context) => AThingGuwanPage(),
          '/apage/usepage': (context) => AUsePage(),
          '/apage/usepage/baopage': (context) => AUseBaoPage(),
          '/bankpage': (context) => BankPage(),
          '/bankpage/getpage': (context) => BankGetPage(),
          '/bankpage/juanpage': (context) => BankJuanPage(),
          '/bankpage/juanpage/jiangpage': (context) => BankJuanJiangPage(),
          '/bankpage/juanpage/jiangpage/jifenpage': (context) =>
              BankJuanJiangJifPage(),
          '/bankpage/juanpage/realpage': (context) => BankJuanRealPage(),
          '/bankpage/storepage': (context) => BankStorePage(),
          '/calcpage': (context) => CalcPage(),
          '/calcpage/shoppage': (context) => CalcShopPage(),
          '/calcpage/startpage': (context) => CalcStartPage(),
          '/calcpage/startpage/addsubpage': (context) => CalcAddsubPage(),
          '/calcpage/startpage/divpage': (context) => CalcDivPage(),
          '/calcpage/startpage/polypage': (context) => CalcPolyPage(),
          '/calcpage/startpage/timpage': (context) => CalcTimPage(),
          '/ownpage': (context) => OwnPage(),
          '/ownpage/lihepage': (context) => LihePage(),
          '/ownpage/thingpage': (context) => ThingPage(),
          '/ownpage/thingpage/mainpage': (context) => ThingMainPage(),
          '/ownpage/thingpage/mainpage/baoshipage': (context) =>
              ThingMainBaoshiPage(),
          '/ownpage/thingpage/mainpage/baoshipage/getpage': (context) =>
              ThingMainBaoshiGetPage(),
          '/ownpage/thingpage/mainpage/baoshipage/cpage': (context) =>
              ThingMainBaoshiChouPage(),
          '/ownpage/thingpage/mainpage/baoshipage/cpage/c1page': (context) =>
              ThingMainBaoshiChou1Page(),
          '/ownpage/thingpage/mainpage/cardpage': (context) =>
              ThingMainCardPage(),
          '/ownpage/thingpage/mainpage/cardpage/han1page': (context) =>
              ThingMainCardHan1Page(),
          '/ownpage/thingpage/mainpage/cardpage/sang1page': (context) =>
              ThingMainCardSang1Page(),
          '/ownpage/thingpage/mainpage/yinbipage': (context) =>
              ThingMainYinbiPage(),
          '/ownpage/thingpage/shoppage': (context) => ThingShopPage(),
          '/ownpage/thingpage/showpage': (context) => ThingShowPage(),
          '/ownpage/timepage': (context) => TimePage(),
          '/ownpage/tongypage': (context) => TongyPage(),
          '/ownpage/tongypage/jifenpage': (context) => TongyJifenPage(),
          '/settingpage': (context) => SettingPage(),
          '/thingpage': (context) => TSPage(),
          '/thingpage/freepage': (context) => TSFreePage(),
          '/thingpage/jinpage': (context) => TSJinPage(),
          '/thingpage/mangpage': (context) => TSMangPage(),
          '/utilpage': (context) => UtilPage(),
        },
      ),
    );
  }
}
