#!/bin/bash
cd ~/sbuild
cp ~/学习平台/bin/学习平台 .
rm -r AppDir -f
mkdir -p AppDir/usr/share/doc/StudyPlatform/
cp ~/学习平台/LICENSE AppDir/usr/share/doc/StudyPlatform/ 
mkdir -p AppDir/usr/bin/
cp ~/学习平台/util/ AppDir/usr/bin/ -r
cp AppDir/usr/bin/util/* AppDir/usr/bin/
ln -s usr/bin/util AppDir/util
./linuxdeploy-x86_64.AppImage --appdir AppDir --executable 学习平台 -d 学习平台.desktop -i 学习平台.png
./appimagetool-x86_64.AppImage AppDir --runtime-file ./runtime-x86_64
ls *学习平台*.AppImage
tar cavf 学习平台.tar.xz *学习平台*.AppImage
mv 学习平台.tar.xz ~/releases/学习平台/新版本/ 
rm -r 学习平台
cd ~/releases/学习平台/新版本/
if [[ $# -ne 1 ]] ; then
    echo "参数错误";
    exit 1;
else
    chmod +x 学习平台.tar.xz;
    mv 学习平台.tar.xz 学习平台$1.tar.xz;
    sudo chattr +i 学习平台$1.tar.xz
    exit 0;
fi
